# Generated by Django 6.0 on 2025-12-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ccard_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=100)),
                ('cc_num', models.CharField(max_length=300)),
                ('limit', models.FloatField()),
                ('outstanding', models.FloatField(default=0)),
            ],
        ),
    ]
